(defun canonicalise-copyarea-db-file (dir)
  (interactive "D")
  (let ((dbfile (concat dir "/" ".copyarea.db")))
    (if (file-exists-p dbfile)
        (save-excursion
          (set-buffer (find-file-noselect dbfile))
          (goto-char (point-min))
          (forward-line 3)
          (let ((beginning (point)))
            (goto-char (point-max))
            (sort-lines nil beginning (point)))
          (save-buffer)
          (kill-buffer nil)
          (message (concat "Canonicalized " dbfile))))))

