(defun su-command (password command)
  "Prompt for root password and a command, then do the latter as root."
  (interactive "sRoot password: \nsCommand: ")
  (let ((buffer (get-buffer-create "*Shell Command Output*"))
        proc)
    (if (save-excursion
	  (set-buffer buffer)
	  (erase-buffer)
	  (setq proc (start-process "su-emacs" buffer "/bin/su"
				    "-c" command))
	  (goto-char (point-min))
	  (while (not (looking-at "Password:"))
	    (accept-process-output proc)
	    (goto-char (point-min)))
	  (erase-buffer)
	  (send-string proc (concat password "\n"))
	  (while (not (looking-at "\n"))
	    (accept-process-output proc)
	    (goto-char (point-min)))
	  (delete-char 1)
	  (while (not (equal (process-status proc) 'exit))
	    (accept-process-output))
	  (> (buffer-size) 0))
	(set-window-start (display-buffer buffer) 1)
      (message "(Command completed with no output)"))))
