;;; kaesar-pbkdf2-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from kaesar-pbkdf2.el

(autoload 'kaesar-pbkdf2-hmac "kaesar-pbkdf2" "\
PASSWORD as string ITER as integer SIZE as integer return list of byte.
Optional SALT as list (also allow string) of byte.
Optional ALGORITHM should be listed in `hmac-algorithm-blocksizes` .

(fn PASSWORD ITER SIZE &optional SALT ALGORITHM)")
(register-definition-prefixes "kaesar-pbkdf2" '("kaesar-pbkdf2-"))

;;; End of scraped data

(provide 'kaesar-pbkdf2-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; kaesar-pbkdf2-autoloads.el ends here
